CREATE TABLE form_b (
    form_id VARCHAR(36) NOT NULL PRIMARY KEY,
    applicant_name VARCHAR(255) NOT NULL,
    student_number INTEGER NOT NULL,
    institution VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    degree VARCHAR(255) NOT NULL,
    project_title VARCHAR(255) NOT NULL,
    mobile_number VARCHAR(15) NOT NULL,
    email_address VARCHAR(255) NOT NULL,
    supervisor_name VARCHAR(255) NOT NULL,
    supervisor_email VARCHAR(255) NOT NULL,
    project_description TEXT,
    data_nature VARCHAR(255),
    data_origin VARCHAR(255),
    data_public BOOLEAN,
    public_evidence TEXT,
    access_conditions TEXT,
    personal_info BOOLEAN,
    data_anonymized BOOLEAN,
    anonymization_comment TEXT,
    private_permission BOOLEAN,
    permission_details TEXT,
    shortcomings_reported BOOLEAN,
    limitations_reporting TEXT,
    methodology_alignment BOOLEAN,
    data_acknowledgment TEXT,
    original_clearance BOOLEAN,
    participant_permission BOOLEAN,
    data_safekeeping TEXT,
    risk_level VARCHAR(50),
    risk_comments TEXT,
    declaration_full_name VARCHAR(255) NOT NULL,
    declaration_date DATETIME NOT NULL
);