"""Add form_c table

Revision ID: 068424b80c7e
Revises: 5252776e42bf
Create Date: 2025-05-27 17:29:51.051389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068424b80c7e'
down_revision: Union[str, None] = '5252776e42bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('supervisor_comments', sa.Text(), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_signature', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('rejected_or_accepted', sa.Boolean(), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_date', sa.DateTime(), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_comments', sa.Text(), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_signature', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('rejected_or_accepted', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_date', sa.DateTime(), nullable=True))
    op.add_column('form_c', sa.Column('rejected_or_accepted', sa.Boolean(), nullable=True))
    op.alter_column('form_c', 'supervisor_signature',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_c', 'supervisor_signature',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('form_c', 'rejected_or_accepted')
    op.drop_column('form_b', 'supervisor_date')
    op.drop_column('form_b', 'rejected_or_accepted')
    op.drop_column('form_b', 'supervisor_signature')
    op.drop_column('form_b', 'supervisor_comments')
    op.drop_column('form_a', 'supervisor_date')
    op.drop_column('form_a', 'rejected_or_accepted')
    op.drop_column('form_a', 'supervisor_signature')
    op.drop_column('form_a', 'supervisor_comments')
    # ### end Alembic commands ###
