"""Add form_c table

Revision ID: 09968b8977f0
Revises: 1264c7603328
Create Date: 2025-05-26 17:10:26.001549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09968b8977f0'
down_revision: Union[str, None] = '1264c7603328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('population', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('sampling_method', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('sampling_size', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('inclusion_criteria', sa.String(), nullable=True))
    op.alter_column('form_d', 'user_id',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_d', 'user_id',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_column('form_a', 'inclusion_criteria')
    op.drop_column('form_a', 'sampling_size')
    op.drop_column('form_a', 'sampling_method')
    op.drop_column('form_a', 'population')
    # ### end Alembic commands ###
