"""Add missing columns to form_a_requirements

Revision ID: 108f68d5efb4
Revises: d2ca394f2ac8
Create Date: 2025-06-13 16:17:10.846273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '108f68d5efb4'
down_revision: Union[str, None] = 'd2ca394f2ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a_requirements', sa.Column('form_type', sa.String(), nullable=False))
    op.add_column('form_a_requirements', sa.Column('files', sa.Text(), nullable=True))
    op.add_column('form_a_requirements', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_a_requirements', 'updated_at')
    op.drop_column('form_a_requirements', 'files')
    op.drop_column('form_a_requirements', 'form_type')
    # ### end Alembic commands ###
