"""Add or update tables

Revision ID: 10964c91c124
Revises: 5f8c2f030b44
Create Date: 2025-08-06 12:37:34.323536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10964c91c124'
down_revision: Union[str, None] = '5f8c2f030b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('submitted', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('submitted', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('submitted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'submitted')
    op.drop_column('form_b', 'submitted')
    op.drop_column('form_a', 'submitted')
    # ### end Alembic commands ###
