"""Add missing columns to form_a_requirements

Revision ID: 124d7eaf2878
Revises: 108f68d5efb4
Create Date: 2025-06-14 12:43:45.903696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124d7eaf2878'
down_revision: Union[str, None] = '108f68d5efb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('staff_number', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('specialisation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'specialisation')
    op.drop_column('users', 'staff_number')
    # ### end Alembic commands ###
