"""Add form_c table

Revision ID: 1264c7603328
Revises: 6ec09527cbe9
Create Date: 2025-05-26 15:12:12.417482

"""
from typing import Sequence, Union
from sqlalchemy import Text
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1264c7603328'
down_revision: Union[str, None] = '6ec09527cbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('application_name', sa.String(length=100), nullable=True))
    op.add_column('form_c', sa.Column('age_under_18_or_over_65', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('uj_employees', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('non_vulnerable_context', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('non_english', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('own_students', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('poverty', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('no_education', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('vulnerable_other_description', sa.Text(), nullable=True))
    op.add_column('form_c', sa.Column('consent_violation', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('discomfiture', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('deception', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('sensitive_issues', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('prejudicial_info', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('intrusive', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('illegal', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('direct_social_info', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('identifiable_records', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('psychology_tests', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('researcher_risk', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('activity_other_description', sa.Text(), nullable=True))
    op.add_column('form_c', sa.Column('incentives', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('participant_costs', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('researcher_interest', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('conflict_of_interest', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('uj_premises', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('uj_facilities', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('uj_funding', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('vulnerable_groups', postgresql.JSON(astext_type=Text()), nullable=True))
    op.add_column('form_c', sa.Column('research_activities', postgresql.JSON(astext_type=Text()), nullable=True))
    op.add_column('form_c', sa.Column('activities_comments', sa.Text(), nullable=True))
    op.add_column('form_c', sa.Column('additional_considerations', postgresql.JSON(astext_type=Text()), nullable=True))
    op.add_column('form_c', sa.Column('considerations_comments', sa.Text(), nullable=True))
    op.add_column('form_c', sa.Column('risk_justification', sa.Text(), nullable=True))
    op.add_column('form_c', sa.Column('summary_title', sa.Text(), nullable=True))
    op.add_column('form_c', sa.Column('declaration_name', sa.String(length=200), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_comments', sa.Text(), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_signature', sa.String(length=200), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_date', sa.DateTime(), nullable=True))
    op.add_column('form_c', sa.Column('status', sa.String(length=50), nullable=True))
    op.alter_column('form_c', 'student_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('form_c', 'institution',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('form_c', 'department',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('form_c', 'degree',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('form_c', 'project_title',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('form_c', 'mobile_number',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('form_c', 'supervisor_name',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('form_c', 'supervisor_email',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('form_c', 'vulnerable',
               existing_type=mssql.VARBINARY(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('form_c', 'risk_level',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('form_c', 'full_name',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_column('form_c', 'ethical_clearance')
    op.drop_column('form_c', 'participant_consent')
    op.drop_column('form_c', 'activity_other')
    op.drop_column('form_c', 'risk_assessment')
    op.drop_column('form_c', 'consent_details')
    op.drop_column('form_c', 'applicant_name')
    op.drop_column('form_c', 'vulnerable_other')
    op.drop_column('form_c', 'consideration_comments')
    op.drop_column('form_c', 'eclaration_name')
    op.drop_column('form_c', 'declaration_date')
    op.drop_column('form_c', 'activity_comments')
    op.drop_column('form_c', 'declaration_full_name')
    op.drop_column('form_c', 'consideration')
    op.drop_column('form_c', 'justify')
    op.drop_column('form_c', 'activity')
    op.drop_column('form_c', 'clearance_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('clearance_details', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('activity', mssql.VARBINARY(), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('justify', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('consideration', mssql.VARBINARY(), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('declaration_full_name', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('activity_comments', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('declaration_date', sa.DATETIME(), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('eclaration_name', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('consideration_comments', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('vulnerable_other', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('applicant_name', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('consent_details', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('risk_assessment', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('activity_other', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('participant_consent', mssql.BIT(), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('ethical_clearance', mssql.BIT(), autoincrement=False, nullable=True))
    op.alter_column('form_c', 'full_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('form_c', 'risk_level',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('form_c', 'vulnerable',
               existing_type=sa.Boolean(),
               type_=mssql.VARBINARY(),
               existing_nullable=True)
    op.alter_column('form_c', 'supervisor_email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('form_c', 'supervisor_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('form_c', 'mobile_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('form_c', 'project_title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('form_c', 'degree',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('form_c', 'department',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('form_c', 'institution',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('form_c', 'student_number',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('form_c', 'status')
    op.drop_column('form_c', 'supervisor_date')
    op.drop_column('form_c', 'supervisor_signature')
    op.drop_column('form_c', 'supervisor_comments')
    op.drop_column('form_c', 'declaration_name')
    op.drop_column('form_c', 'summary_title')
    op.drop_column('form_c', 'risk_justification')
    op.drop_column('form_c', 'considerations_comments')
    op.drop_column('form_c', 'additional_considerations')
    op.drop_column('form_c', 'activities_comments')
    op.drop_column('form_c', 'research_activities')
    op.drop_column('form_c', 'vulnerable_groups')
    op.drop_column('form_c', 'uj_funding')
    op.drop_column('form_c', 'uj_facilities')
    op.drop_column('form_c', 'uj_premises')
    op.drop_column('form_c', 'conflict_of_interest')
    op.drop_column('form_c', 'researcher_interest')
    op.drop_column('form_c', 'participant_costs')
    op.drop_column('form_c', 'incentives')
    op.drop_column('form_c', 'activity_other_description')
    op.drop_column('form_c', 'researcher_risk')
    op.drop_column('form_c', 'psychology_tests')
    op.drop_column('form_c', 'identifiable_records')
    op.drop_column('form_c', 'direct_social_info')
    op.drop_column('form_c', 'illegal')
    op.drop_column('form_c', 'intrusive')
    op.drop_column('form_c', 'prejudicial_info')
    op.drop_column('form_c', 'sensitive_issues')
    op.drop_column('form_c', 'deception')
    op.drop_column('form_c', 'discomfiture')
    op.drop_column('form_c', 'consent_violation')
    op.drop_column('form_c', 'vulnerable_other_description')
    op.drop_column('form_c', 'no_education')
    op.drop_column('form_c', 'poverty')
    op.drop_column('form_c', 'own_students')
    op.drop_column('form_c', 'non_english')
    op.drop_column('form_c', 'non_vulnerable_context')
    op.drop_column('form_c', 'uj_employees')
    op.drop_column('form_c', 'age_under_18_or_over_65')
    op.drop_column('form_c', 'application_name')
    # ### end Alembic commands ###
