"""Add or update tables

Revision ID: 13fd7448ff14
Revises: 
Create Date: 2025-07-28 15:36:04.796669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13fd7448ff14'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('data_nature', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('data_origin', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('access_conditions', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('personal_info', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('personal_info_comment', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('data_anonymized', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('anonymization_comment', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('permission_details', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('shortcomings_reported', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('limitations_reporting', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('methodology_alignment', sa.String(length=256), nullable=True))
    op.add_column('form_a', sa.Column('data_acknowledgment', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_a', 'data_acknowledgment')
    op.drop_column('form_a', 'methodology_alignment')
    op.drop_column('form_a', 'limitations_reporting')
    op.drop_column('form_a', 'shortcomings_reported')
    op.drop_column('form_a', 'permission_details')
    op.drop_column('form_a', 'anonymization_comment')
    op.drop_column('form_a', 'data_anonymized')
    op.drop_column('form_a', 'personal_info_comment')
    op.drop_column('form_a', 'personal_info')
    op.drop_column('form_a', 'access_conditions')
    op.drop_column('form_a', 'data_origin')
    op.drop_column('form_a', 'data_nature')
    # ### end Alembic commands ###
