"""Add form_c table

Revision ID: 1610bc669000
Revises: f964c4849959
Create Date: 2025-06-01 11:53:26.585442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1610bc669000'
down_revision: Union[str, None] = 'f964c4849959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('ethics_commettee_comments', sa.Text(), nullable=True))
    op.add_column('form_a', sa.Column('ethics_commettee_signature', sa.Text(), nullable=True))
    op.add_column('form_a', sa.Column('ethics_commettee_date', sa.DateTime(), nullable=True))
    op.add_column('form_a', sa.Column('ethics_commetee_status', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('ethics_commettee_comments', sa.Text(), nullable=True))
    op.add_column('form_b', sa.Column('ethics_commettee_signature', sa.Text(), nullable=True))
    op.add_column('form_b', sa.Column('ethics_commettee_date', sa.DateTime(), nullable=True))
    op.add_column('form_b', sa.Column('ethics_commetee_status', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('ethics_commettee_comments', sa.Text(), nullable=True))
    op.add_column('form_c', sa.Column('ethics_commettee_signature', sa.Text(), nullable=True))
    op.add_column('form_c', sa.Column('ethics_commettee_date', sa.DateTime(), nullable=True))
    op.add_column('form_c', sa.Column('ethics_commetee_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'ethics_commetee_status')
    op.drop_column('form_c', 'ethics_commettee_date')
    op.drop_column('form_c', 'ethics_commettee_signature')
    op.drop_column('form_c', 'ethics_commettee_comments')
    op.drop_column('form_b', 'ethics_commetee_status')
    op.drop_column('form_b', 'ethics_commettee_date')
    op.drop_column('form_b', 'ethics_commettee_signature')
    op.drop_column('form_b', 'ethics_commettee_comments')
    op.drop_column('form_a', 'ethics_commetee_status')
    op.drop_column('form_a', 'ethics_commettee_date')
    op.drop_column('form_a', 'ethics_commettee_signature')
    op.drop_column('form_a', 'ethics_commettee_comments')
    # ### end Alembic commands ###
