"""initial_migration

Revision ID: 1f75b3c2a8d1
Revises: a082e94d6413
Create Date: 2025-05-20 16:34:31.095712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f75b3c2a8d1'
down_revision: Union[str, None] = 'a082e94d6413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_b', sa.Column('original_clearance', sa.String(length=20), nullable=True))
    op.add_column('form_b', sa.Column('participant_permission', sa.String(length=20), nullable=True))
    op.add_column('form_b', sa.Column('data_safekeeping', sa.Text(), nullable=True))
    op.add_column('form_b', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('form_b', sa.Column('risk_comments', sa.Text(), nullable=True))
    op.add_column('form_b', sa.Column('declaration_name', sa.String(length=150), nullable=True))
    op.add_column('form_b', sa.Column('full_name', sa.String(length=150), nullable=True))
    op.add_column('form_b', sa.Column('declaration_date', sa.DateTime(), nullable=True))
    op.add_column('form_b', sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('form_c', sa.Column('user_id', sa.String(length=255), nullable=False))
    op.alter_column('form_c', 'applicant_name',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'student_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('form_c', 'institution',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'department',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'degree',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'project_title',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'mobile_number',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'email_address',
               existing_type=sa.VARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'supervisor_name',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'supervisor_email',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'declaration_full_name',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('form_c', 'declaration_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('form_c', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('student_id', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.alter_column('form_c', 'declaration_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('form_c', 'declaration_full_name',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('form_c', 'supervisor_email',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('form_c', 'supervisor_name',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('form_c', 'email_address',
               existing_type=sa.VARCHAR(length=120, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('form_c', 'mobile_number',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('form_c', 'project_title',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('form_c', 'degree',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('form_c', 'department',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('form_c', 'institution',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('form_c', 'student_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('form_c', 'applicant_name',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_column('form_c', 'user_id')
    op.drop_column('form_b', 'submitted_at')
    op.drop_column('form_b', 'declaration_date')
    op.drop_column('form_b', 'full_name')
    op.drop_column('form_b', 'declaration_name')
    op.drop_column('form_b', 'risk_comments')
    op.drop_column('form_b', 'risk_level')
    op.drop_column('form_b', 'data_safekeeping')
    op.drop_column('form_b', 'participant_permission')
    op.drop_column('form_b', 'original_clearance')
    # ### end Alembic commands ###
