"""Add missing columns to form_a_requirements

Revision ID: 21d4f8a830e1
Revises: 3e40a1ea3a30
Create Date: 2025-06-06 11:22:38.530300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d4f8a830e1'
down_revision: Union[str, None] = '3e40a1ea3a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('applicant_name', sa.String(length=100), nullable=True))
    op.drop_column('form_c', 'application_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('application_name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('form_c', 'applicant_name')
    # ### end Alembic commands ###
