"""Add missing columns to form_a_requirements

Revision ID: 2cf57b8972c9
Revises: 96f4d21e6eab
Create Date: 2025-06-18 16:04:25.634628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf57b8972c9'
down_revision: Union[str, None] = '96f4d21e6eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'watched',
        sa.Column('watched_id', sa.String(255), nullable=False),
        sa.Column('user_id', sa.String(255), nullable=False),
        sa.Column('watched', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('watched_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched')
    # ### end Alembic commands ###
