"""Add form_c table

Revision ID: 35c7d05496f7
Revises: 068424b80c7e
Create Date: 2025-05-31 10:59:17.232809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c7d05496f7'
down_revision: Union[str, None] = '068424b80c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('consideration_comments', sa.String(), nullable=True))
    op.alter_column('form_c', 'supervisor_signature',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_c', 'supervisor_signature',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('form_c', 'consideration_comments')
    # ### end Alembic commands ###
