"""Initial migration

Revision ID: 3afaf3648822
Revises: 
Create Date: 2025-08-01 03:29:53.239945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afaf3648822'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('certificate_heading', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('certificate_modified', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('certificate_heading', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('certificate_modified', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('certificate_heading', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('certificate_modified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'certificate_modified')
    op.drop_column('form_c', 'certificate_heading')
    op.drop_column('form_b', 'certificate_modified')
    op.drop_column('form_b', 'certificate_heading')
    op.drop_column('form_a', 'certificate_modified')
    op.drop_column('form_a', 'certificate_heading')
    # ### end Alembic commands ###
