"""Add missing columns to form_a_requirements

Revision ID: 3d1678038745
Revises: d551848b85ce
Create Date: 2025-06-12 10:07:46.856769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1678038745'
down_revision: Union[str, None] = 'd551848b85ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_b', sa.Column('org_permission_comment', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('waiver_comment', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('form_a_comment', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('questions_comment', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('consent_comment', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('proposal_comment', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_feedback', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('recommendation', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('signature_date', sa.DateTime(), nullable=True))
    op.drop_column('form_b', 'supervisor_comments')
    op.add_column('form_c', sa.Column('org_permission_comment', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('waiver_comment', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('form_a_comment', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('questions_comment', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('consent_comment', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('proposal_comment', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_feedback', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('recommendation', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('signature_date', sa.DateTime(), nullable=True))
    op.alter_column('form_c', 'supervisor_signature',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('form_c', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('status', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.alter_column('form_c', 'supervisor_signature',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('form_c', 'signature_date')
    op.drop_column('form_c', 'recommendation')
    op.drop_column('form_c', 'supervisor_feedback')
    op.drop_column('form_c', 'proposal_comment')
    op.drop_column('form_c', 'consent_comment')
    op.drop_column('form_c', 'questions_comment')
    op.drop_column('form_c', 'form_a_comment')
    op.drop_column('form_c', 'waiver_comment')
    op.drop_column('form_c', 'org_permission_comment')
    op.add_column('form_b', sa.Column('supervisor_comments', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('form_b', 'signature_date')
    op.drop_column('form_b', 'recommendation')
    op.drop_column('form_b', 'supervisor_feedback')
    op.drop_column('form_b', 'proposal_comment')
    op.drop_column('form_b', 'consent_comment')
    op.drop_column('form_b', 'questions_comment')
    op.drop_column('form_b', 'form_a_comment')
    op.drop_column('form_b', 'waiver_comment')
    op.drop_column('form_b', 'org_permission_comment')
    # ### end Alembic commands ###
