"""Add missing columns to form_a_requirements

Revision ID: 3e40a1ea3a30
Revises: b1a5d80f1906
Create Date: 2025-06-06 10:17:39.583307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e40a1ea3a30'
down_revision: Union[str, None] = 'b1a5d80f1906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_b', 'declaration_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_b', 'declaration_date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
