"""Fix watched_id type

Revision ID: 464dedb4cf3f
Revises: 62f9b6b37dd0
Create Date: 2025-07-09 15:07:14.574928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464dedb4cf3f'
down_revision: Union[str, None] = '62f9b6b37dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('submitted_to_rec', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('submitted_to_rec', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('submitted_to_rec', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'submitted_to_rec')
    op.drop_column('form_b', 'submitted_to_rec')
    op.drop_column('form_a', 'submitted_to_rec')
    # ### end Alembic commands ###
