"""create initial tables

Revision ID: 4dcd9dc31e4d
Revises: 54827b3f3d24
Create Date: 2025-06-03 13:37:32.805198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '4dcd9dc31e4d'
down_revision: Union[str, None] = '54827b3f3d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a_requirements', sa.Column('permission_letter', sa.String(length=255), nullable=True))
    op.add_column('form_a_requirements', sa.Column('has_clearance', sa.Boolean(), nullable=True))
    op.add_column('form_a_requirements', sa.Column('prior_clearance', sa.Boolean(), nullable=True))
    op.add_column('form_a_requirements', sa.Column('need_jbs_clearance', sa.String(length=255), nullable=True))
    op.add_column('form_a_requirements', sa.Column('prior_clearance1', sa.String(length=255), nullable=True))
    op.add_column('form_a_requirements', sa.Column('need_jbs_clearance1', sa.Boolean(), nullable=True))
    op.add_column('form_a_requirements', sa.Column('has_ethics_evidence', sa.Boolean(), nullable=True))
    op.add_column('form_a_requirements', sa.Column('ethics_evidence', sa.Boolean(), nullable=True))
    op.alter_column('form_a_requirements', 'user_id',
               existing_type=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               nullable=True)
    op.alter_column('form_a_requirements', 'needs_permission',
               existing_type=mssql.BIT(),
               nullable=True)
    op.alter_column('form_a_requirements', 'company_requires_jbs',
               existing_type=mssql.BIT(),
               nullable=True)
    op.alter_column('form_a_requirements', 'research_tools_path',
               existing_type=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               nullable=True)
    op.alter_column('form_a_requirements', 'proposal_path',
               existing_type=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               nullable=True)
    op.alter_column('form_a_requirements', 'impact_assessment_path',
               existing_type=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               nullable=True)
    op.drop_column('form_a_requirements', 'permission_letter_path')
    op.drop_column('form_a_requirements', 'has_prior_clearance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a_requirements', sa.Column('has_prior_clearance', mssql.BIT(), autoincrement=False, nullable=False))
    op.add_column('form_a_requirements', sa.Column('permission_letter_path', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))
    op.alter_column('form_a_requirements', 'impact_assessment_path',
               existing_type=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               nullable=False)
    op.alter_column('form_a_requirements', 'proposal_path',
               existing_type=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               nullable=False)
    op.alter_column('form_a_requirements', 'research_tools_path',
               existing_type=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               nullable=False)
    op.alter_column('form_a_requirements', 'company_requires_jbs',
               existing_type=mssql.BIT(),
               nullable=False)
    op.alter_column('form_a_requirements', 'needs_permission',
               existing_type=mssql.BIT(),
               nullable=False)
    op.alter_column('form_a_requirements', 'user_id',
               existing_type=sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'),
               nullable=False)
    op.drop_column('form_a_requirements', 'ethics_evidence')
    op.drop_column('form_a_requirements', 'has_ethics_evidence')
    op.drop_column('form_a_requirements', 'need_jbs_clearance1')
    op.drop_column('form_a_requirements', 'prior_clearance1')
    op.drop_column('form_a_requirements', 'need_jbs_clearance')
    op.drop_column('form_a_requirements', 'prior_clearance')
    op.drop_column('form_a_requirements', 'has_clearance')
    op.drop_column('form_a_requirements', 'permission_letter')
    # ### end Alembic commands ###
