"""Add missing columns to form_a_requirements

Revision ID: 51bff61b8ff5
Revises: 21d4f8a830e1
Create Date: 2025-06-06 14:34:45.799287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bff61b8ff5'
down_revision: Union[str, None] = '21d4f8a830e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('remove_identifiers', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('encryption', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('pseudonyms', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('focus_group_warning', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_a', 'focus_group_warning')
    op.drop_column('form_a', 'pseudonyms')
    op.drop_column('form_a', 'encryption')
    op.drop_column('form_a', 'remove_identifiers')
    # ### end Alembic commands ###
