"""Add form_c table

Revision ID: 5252776e42bf
Revises: 09968b8977f0
Create Date: 2025-05-26 17:33:13.445061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5252776e42bf'
down_revision: Union[str, None] = '09968b8977f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('secure_location', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('password_protected', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('protected_place', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('retention', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_a', 'retention')
    op.drop_column('form_a', 'protected_place')
    op.drop_column('form_a', 'password_protected')
    op.drop_column('form_a', 'secure_location')
    # ### end Alembic commands ###
