"""Fix watched table

Revision ID: 57bcf6cccc69
Revises: b3c8df70beea
Create Date: 2025-06-22 11:48:08.663593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bcf6cccc69'
down_revision: Union[str, None] = 'b3c8df70beea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('certificate_code', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('certificate_code', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('certificate_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'certificate_code')
    op.drop_column('form_b', 'certificate_code')
    op.drop_column('form_a', 'certificate_code')
    # ### end Alembic commands ###
