"""Add or update tables

Revision ID: 58a7d3b251fb
Revises: 
Create Date: 2025-08-06 23:21:20.242213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a7d3b251fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_a', 'certificate_condition_8')
    op.drop_column('form_a', 'certificate_condition_4')
    op.drop_column('form_a', 'certificate_condition_2')
    op.drop_column('form_a', 'certificate_condition_6')
    op.drop_column('form_a', 'certificate_condition_5')
    op.drop_column('form_a', 'certificate_condition_7')
    op.drop_column('form_a', 'certificate_condition_9')
    op.drop_column('form_a', 'certificate_condition_3')
    op.drop_column('form_b', 'certificate_condition_8')
    op.drop_column('form_b', 'certificate_condition_4')
    op.drop_column('form_b', 'certificate_condition_2')
    op.drop_column('form_b', 'certificate_condition_6')
    op.drop_column('form_b', 'certificate_condition_5')
    op.drop_column('form_b', 'certificate_condition_7')
    op.drop_column('form_b', 'certificate_condition_9')
    op.drop_column('form_b', 'certificate_condition_3')
    op.drop_column('form_c', 'certificate_condition_8')
    op.drop_column('form_c', 'certificate_condition_4')
    op.drop_column('form_c', 'certificate_condition_2')
    op.drop_column('form_c', 'certificate_condition_6')
    op.drop_column('form_c', 'certificate_condition_5')
    op.drop_column('form_c', 'certificate_condition_7')
    op.drop_column('form_c', 'certificate_condition_9')
    op.drop_column('form_c', 'certificate_condition_3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('certificate_condition_3', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('certificate_condition_9', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('certificate_condition_7', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('certificate_condition_5', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('certificate_condition_6', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('certificate_condition_2', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('certificate_condition_4', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_c', sa.Column('certificate_condition_8', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_b', sa.Column('certificate_condition_3', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_b', sa.Column('certificate_condition_9', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_b', sa.Column('certificate_condition_7', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_b', sa.Column('certificate_condition_5', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_b', sa.Column('certificate_condition_6', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_b', sa.Column('certificate_condition_2', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_b', sa.Column('certificate_condition_4', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_b', sa.Column('certificate_condition_8', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('certificate_condition_3', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('certificate_condition_9', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('certificate_condition_7', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('certificate_condition_5', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('certificate_condition_6', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('certificate_condition_2', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('certificate_condition_4', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('certificate_condition_8', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
