"""Fix watched table

Revision ID: 5adbcb6b6458
Revises: 302596836941
Create Date: 2025-06-19 08:52:06.843841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5adbcb6b6458'
down_revision: Union[str, None] = '302596836941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('rec_date', sa.DateTime(), nullable=True))
    op.add_column('form_b', sa.Column('rec_date', sa.DateTime(), nullable=True))
    op.alter_column('form_b', 'declaration_date',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('form_c', sa.Column('rec_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'rec_date')
    op.alter_column('form_b', 'declaration_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('form_b', 'rec_date')
    op.drop_column('form_a', 'rec_date')
    # ### end Alembic commands ###
