"""Fix watched_id type

Revision ID: 5ba2678faf02
Revises: b2eae445fb82
Create Date: 2025-07-09 19:07:39.182393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba2678faf02'
down_revision: Union[str, None] = 'b2eae445fb82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec', sa.Column('full_name', sa.String(), nullable=True))
    op.drop_column('rec', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec', sa.Column('status', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('rec', 'full_name')
    # ### end Alembic commands ###
