"""Add missing columns to form_a_requirements

Revision ID: 5c485d9bccf2
Revises: b6684e0368fc
Create Date: 2025-06-18 10:47:07.682275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c485d9bccf2'
down_revision: Union[str, None] = 'b6684e0368fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('review_date1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_org_permission_status1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_org_permission_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_waiver_status1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_waiver_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_form_status1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_form_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_questions_status1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_questions_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_consent_status1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_consent_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_proposal_status1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_proposal_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_additional_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_recommendation1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_supervisor_signature1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('review_signature_date1', sa.DateTime(), nullable=True))
    op.add_column('form_b', sa.Column('review_date1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_org_permission_status1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_org_permission_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_waiver_status1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_waiver_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_form_status1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_form_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_questions_status1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_questions_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_consent_status1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_consent_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_proposal_status1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_proposal_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_additional_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_recommendation1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_supervisor_signature1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('review_signature_date1', sa.DateTime(), nullable=True))
    op.add_column('form_c', sa.Column('review_date1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_org_permission_status1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_org_permission_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_waiver_status1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_waiver_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_form_status1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_form_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_questions_status1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_questions_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_consent_status1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_consent_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_proposal_status1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_proposal_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_additional_comments1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_recommendation1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_supervisor_signature1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('review_signature_date1', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'review_signature_date1')
    op.drop_column('form_c', 'review_supervisor_signature1')
    op.drop_column('form_c', 'review_recommendation1')
    op.drop_column('form_c', 'review_additional_comments1')
    op.drop_column('form_c', 'review_proposal_comments1')
    op.drop_column('form_c', 'review_proposal_status1')
    op.drop_column('form_c', 'review_consent_comments1')
    op.drop_column('form_c', 'review_consent_status1')
    op.drop_column('form_c', 'review_questions_comments1')
    op.drop_column('form_c', 'review_questions_status1')
    op.drop_column('form_c', 'review_form_comments1')
    op.drop_column('form_c', 'review_form_status1')
    op.drop_column('form_c', 'review_waiver_comments1')
    op.drop_column('form_c', 'review_waiver_status1')
    op.drop_column('form_c', 'review_org_permission_comments1')
    op.drop_column('form_c', 'review_org_permission_status1')
    op.drop_column('form_c', 'review_date1')
    op.drop_column('form_b', 'review_signature_date1')
    op.drop_column('form_b', 'review_supervisor_signature1')
    op.drop_column('form_b', 'review_recommendation1')
    op.drop_column('form_b', 'review_additional_comments1')
    op.drop_column('form_b', 'review_proposal_comments1')
    op.drop_column('form_b', 'review_proposal_status1')
    op.drop_column('form_b', 'review_consent_comments1')
    op.drop_column('form_b', 'review_consent_status1')
    op.drop_column('form_b', 'review_questions_comments1')
    op.drop_column('form_b', 'review_questions_status1')
    op.drop_column('form_b', 'review_form_comments1')
    op.drop_column('form_b', 'review_form_status1')
    op.drop_column('form_b', 'review_waiver_comments1')
    op.drop_column('form_b', 'review_waiver_status1')
    op.drop_column('form_b', 'review_org_permission_comments1')
    op.drop_column('form_b', 'review_org_permission_status1')
    op.drop_column('form_b', 'review_date1')
    op.drop_column('form_a', 'review_signature_date1')
    op.drop_column('form_a', 'review_supervisor_signature1')
    op.drop_column('form_a', 'review_recommendation1')
    op.drop_column('form_a', 'review_additional_comments1')
    op.drop_column('form_a', 'review_proposal_comments1')
    op.drop_column('form_a', 'review_proposal_status1')
    op.drop_column('form_a', 'review_consent_comments1')
    op.drop_column('form_a', 'review_consent_status1')
    op.drop_column('form_a', 'review_questions_comments1')
    op.drop_column('form_a', 'review_questions_status1')
    op.drop_column('form_a', 'review_form_comments1')
    op.drop_column('form_a', 'review_form_status1')
    op.drop_column('form_a', 'review_waiver_comments1')
    op.drop_column('form_a', 'review_waiver_status1')
    op.drop_column('form_a', 'review_org_permission_comments1')
    op.drop_column('form_a', 'review_org_permission_status1')
    op.drop_column('form_a', 'review_date1')
    # ### end Alembic commands ###
