"""Fix watched table

Revision ID: 5cbd18140597
Revises: cf237ad1de03
Create Date: 2025-06-18 22:09:14.734513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cbd18140597'
down_revision: Union[str, None] = 'cf237ad1de03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('review_status', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('review_status', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('review_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'review_status')
    op.drop_column('form_b', 'review_status')
    op.drop_column('form_a', 'review_status')
    # ### end Alembic commands ###
