"""Add form_c table

Revision ID: 5e90283d983d
Revises: 35c7d05496f7
Create Date: 2025-05-31 12:12:09.370722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e90283d983d'
down_revision: Union[str, None] = '35c7d05496f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('activity_comments', sa.String(), nullable=True))
    op.alter_column('form_c', 'project_title',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('form_c', 'summary_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('summary_title', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.alter_column('form_c', 'project_title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('form_c', 'activity_comments')
    # ### end Alembic commands ###
