"""Fix watched_id type

Revision ID: 62f9b6b37dd0
Revises: 
Create Date: 2025-07-08 14:46:49.810306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f9b6b37dd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('status', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('status', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'status')
    op.drop_column('form_b', 'status')
    op.drop_column('form_a', 'status')
    # ### end Alembic commands ###
