"""Fix watched table

Revision ID: 77d7f0c85b40
Revises: 5cf7b8bd9b66
Create Date: 2025-06-22 14:42:29.139014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d7f0c85b40'
down_revision: Union[str, None] = '5cf7b8bd9b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('pdf_file_path', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('pdf_file_path', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('pdf_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'pdf_file_path')
    op.drop_column('form_b', 'pdf_file_path')
    op.drop_column('form_a', 'pdf_file_path')
    # ### end Alembic commands ###
