"""Add missing columns to form_a_requirements

Revision ID: 7a3cde0a05b6
Revises: b2c90d453c8a
Create Date: 2025-06-17 11:36:06.369938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3cde0a05b6'
down_revision: Union[str, None] = 'b2c90d453c8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('rec_comments', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('rec_status', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('rec_comments', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('rec_status', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('rec_comments', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('rec_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'rec_status')
    op.drop_column('form_c', 'rec_comments')
    op.drop_column('form_b', 'rec_status')
    op.drop_column('form_b', 'rec_comments')
    op.drop_column('form_a', 'rec_status')
    op.drop_column('form_a', 'rec_comments')
    # ### end Alembic commands ###
