"""Fix watched_id type

Revision ID: 7c950069ecaf
Revises: f611d3b12ead
Create Date: 2025-07-01 15:22:54.198072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c950069ecaf'
down_revision: Union[str, None] = 'f611d3b12ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('form_review_comment', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('form_review_comment1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('form_review_comment', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('form_review_comment1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('form_review_comment', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('form_review_comment1', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'form_review_comment1')
    op.drop_column('form_c', 'form_review_comment')
    op.drop_column('form_b', 'form_review_comment1')
    op.drop_column('form_b', 'form_review_comment')
    op.drop_column('form_a', 'form_review_comment1')
    op.drop_column('form_a', 'form_review_comment')
    # ### end Alembic commands ###
