"""Initial migration

Revision ID: 7cd446ab5c72
Revises: 
Create Date: 2025-07-01 23:01:15.074381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd446ab5c72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('form_review_comment', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('form_reviewed_by', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('form_review_comment1', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('form_reviewed_by1', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('form_review_comment', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('form_reviewed_by', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('form_review_comment1', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('form_reviewed_by1', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('form_review_comment', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('form_reviewed_by', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('form_review_comment1', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('form_reviewed_by1', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'form_reviewed_by1')
    op.drop_column('form_c', 'form_review_comment1')
    op.drop_column('form_c', 'form_reviewed_by')
    op.drop_column('form_c', 'form_review_comment')
    op.drop_column('form_b', 'form_reviewed_by1')
    op.drop_column('form_b', 'form_review_comment1')
    op.drop_column('form_b', 'form_reviewed_by')
    op.drop_column('form_b', 'form_review_comment')
    op.drop_column('form_a', 'form_reviewed_by1')
    op.drop_column('form_a', 'form_review_comment1')
    op.drop_column('form_a', 'form_reviewed_by')
    op.drop_column('form_a', 'form_review_comment')
    # ### end Alembic commands ###
