"""Fix watched table

Revision ID: 82628a0d1b55
Revises: 57bcf6cccc69
Create Date: 2025-06-22 12:01:30.065050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82628a0d1b55'
down_revision: Union[str, None] = '57bcf6cccc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('certificate_issued', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('form_b', sa.Column('certificate_issued', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('form_c', sa.Column('certificate_issued', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'certificate_issued')
    op.drop_column('form_b', 'certificate_issued')
    op.drop_column('form_a', 'certificate_issued')
    # ### end Alembic commands ###
