"""Fix watched table

Revision ID: 8d2a39688d7d
Revises: 5cbd18140597
Create Date: 2025-06-18 22:10:50.196022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2a39688d7d'
down_revision: Union[str, None] = '5cbd18140597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('review_status1', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('review_status1', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('review_status1', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'review_status1')
    op.drop_column('form_b', 'review_status1')
    op.drop_column('form_a', 'review_status1')
    # ### end Alembic commands ###
