"""Add missing columns to form_a_requirements

Revision ID: 980b635092a1
Revises: 51bff61b8ff5
Create Date: 2025-06-06 14:56:50.289992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980b635092a1'
down_revision: Union[str, None] = '51bff61b8ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('in_depth', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('semi_structured', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('unstructured', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_a', 'unstructured')
    op.drop_column('form_a', 'semi_structured')
    op.drop_column('form_a', 'in_depth')
    # ### end Alembic commands ###
