"""Initial migration

Revision ID: 9d225d2f6456
Revises: 
Create Date: 2025-08-13 01:45:41.681006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d225d2f6456'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'),
               type_=sa.Enum('STUDENT', 'SUPERVISOR', 'ADMIN', 'REC', 'REVIEWER', 'DEAN', 'SUPER_ADMIN', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'SUPERVISOR', 'ADMIN', 'REC', 'REVIEWER', 'DEAN', 'SUPER_ADMIN', name='userrole'),
               type_=sa.VARCHAR(length=10, collation='Latin1_General_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
