"""initial_migration

Revision ID: a082e94d6413
Revises: c40ba8228910
Create Date: 2025-05-20 14:25:22.028574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a082e94d6413'
down_revision: Union[str, None] = 'c40ba8228910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_b',
    sa.Column('form_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('need_permission', sa.Boolean(), nullable=True),
    sa.Column('permission_letter', sa.String(length=255), nullable=True),
    sa.Column('has_clearance', sa.Boolean(), nullable=True),
    sa.Column('prior_clearance', sa.String(length=255), nullable=True),
    sa.Column('has_ethics_evidence', sa.Boolean(), nullable=True),
    sa.Column('ethics_evidence', sa.String(length=255), nullable=True),
    sa.Column('proposal', sa.String(length=255), nullable=True),
    sa.Column('applicant_name', sa.String(length=120), nullable=True),
    sa.Column('student_number', sa.String(length=50), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('degree', sa.String(length=120), nullable=True),
    sa.Column('study_title', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('supervisor', sa.String(length=120), nullable=True),
    sa.Column('supervisor_email', sa.String(length=120), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('data_nature', sa.String(length=255), nullable=True),
    sa.Column('data_origin', sa.String(length=255), nullable=True),
    sa.Column('data_public', sa.Boolean(), nullable=True),
    sa.Column('public_evidence', sa.Text(), nullable=True),
    sa.Column('access_conditions', sa.Text(), nullable=True),
    sa.Column('personal_info', sa.Boolean(), nullable=True),
    sa.Column('data_anonymized', sa.String(length=20), nullable=True),
    sa.Column('anonymization_comment', sa.Text(), nullable=True),
    sa.Column('private_permission', sa.Boolean(), nullable=True),
    sa.Column('permission_details', sa.Text(), nullable=True),
    sa.Column('shortcomings_reported', sa.Boolean(), nullable=True),
    sa.Column('limitations_reporting', sa.Text(), nullable=True),
    sa.Column('methodology_alignment', sa.Boolean(), nullable=True),
    sa.Column('data_acknowledgment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('form_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_b')
    # ### end Alembic commands ###
