"""Updated 5.4 section - removed unused fields, added data_methods

Revision ID: a59eb4d39681
Revises: 087a583c7778
Create Date: 2025-08-06 22:30:51.677576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59eb4d39681'
down_revision: Union[str, None] = '087a583c7778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('data_methods', sa.PickleType(), nullable=True))
    op.add_column('form_a', sa.Column('observation_details', sa.Text(), nullable=True))
    op.add_column('form_a', sa.Column('documents_details', sa.Text(), nullable=True))
    op.add_column('form_a', sa.Column('other_details', sa.Text(), nullable=True))
    op.alter_column('form_a', 'interview_type',
               existing_type=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_column('form_a', 'encryption')
    op.drop_column('form_a', 'pseudonyms')
    op.drop_column('form_a', 'semi_structured')
    op.drop_column('form_a', 'unstructured')
    op.drop_column('form_a', 'remove_identifiers')
    op.drop_column('form_a', 'in_depth')
    op.drop_column('form_a', 'focus_group_warning')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('focus_group_warning', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('in_depth', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('remove_identifiers', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('unstructured', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('semi_structured', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('pseudonyms', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('form_a', sa.Column('encryption', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))
    op.alter_column('form_a', 'interview_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               existing_nullable=True)
    op.drop_column('form_a', 'other_details')
    op.drop_column('form_a', 'documents_details')
    op.drop_column('form_a', 'observation_details')
    op.drop_column('form_a', 'data_methods')
    # ### end Alembic commands ###
