"""Add missing columns to form_a_requirements

Revision ID: a87e20169099
Revises: d140cf7e4c02
Create Date: 2025-06-09 15:22:54.219078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87e20169099'
down_revision: Union[str, None] = 'd140cf7e4c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('apply_comments', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('grant_permission', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_a', 'grant_permission')
    op.drop_column('form_a', 'apply_comments')
    # ### end Alembic commands ###
