"""Add missing columns to form_a_requirements

Revision ID: b2c90d453c8a
Revises: 8b22733373dc
Create Date: 2025-06-17 10:37:54.910848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c90d453c8a'
down_revision: Union[str, None] = '8b22733373dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_a', 'duration_timing',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_a', 'duration_timing',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
