"""Fix watched_id type

Revision ID: b2eae445fb82
Revises: 464dedb4cf3f
Create Date: 2025-07-09 16:05:35.386277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2eae445fb82'
down_revision: Union[str, None] = '464dedb4cf3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rec',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('rec_id', sa.String(length=255), nullable=True),
    sa.Column('form_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rec_comments', sa.String(), nullable=True),
    sa.Column('rec_status', sa.String(), nullable=True),
    sa.Column('rec_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rec')
    # ### end Alembic commands ###
