"""Add or update tables

Revision ID: b3cfe983c05f
Revises: 1969ff109543
Create Date: 2025-08-12 19:33:13.422550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cfe983c05f'
down_revision: Union[str, None] = '1969ff109543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Enum('STUDENT', 'SUPERVISOR', 'ADMIN', 'REC', 'REVIEWER', 'DEAN', 'SUPER_ADMIN', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'SUPERVISOR', 'ADMIN', 'REC', 'REVIEWER', 'DEAN', 'SUPER_ADMIN', name='userrole'),
               type_=sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
