"""Fix watched_id type

Revision ID: b5977039e8c5
Revises: 7c950069ecaf
Create Date: 2025-07-01 15:38:04.480022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5977039e8c5'
down_revision: Union[str, None] = '7c950069ecaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('form_reviewed_by', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('form_reviewed_by1', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('form_reviewed_by', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('form_reviewed_by1', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('form_reviewed_by', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('form_reviewed_by1', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'form_reviewed_by1')
    op.drop_column('form_c', 'form_reviewed_by')
    op.drop_column('form_b', 'form_reviewed_by1')
    op.drop_column('form_b', 'form_reviewed_by')
    op.drop_column('form_a', 'form_reviewed_by1')
    op.drop_column('form_a', 'form_reviewed_by')
    # ### end Alembic commands ###
