"""Initial migration

Revision ID: b8d3a0182eb9
Revises: 
Create Date: 2025-06-22 11:30:00.597908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d3a0182eb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('supervisor_org_permission_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_org_permission_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_waiver_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_waiver_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_form_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_form_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_questions_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_questions_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_consent_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_consent_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_proposal_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_proposal_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_additional_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_recommendation', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_supervisor_signature', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_signature_date', sa.DateTime(), nullable=True))
    op.add_column('form_a', sa.Column('review_status', sa.Boolean(), nullable=True))
    op.add_column('form_a', sa.Column('review_status1', sa.Boolean(), nullable=True))
    op.add_column('form_a', sa.Column('rec_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.alter_column('form_a', 'declaration_date',
               existing_type=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('form_a', 'supervisor_date',
               existing_type=sa.DATETIME(),
               type_=sa.DateTime(timezone=255),
               existing_nullable=True)
    op.add_column('form_b', sa.Column('supervisor_org_permission_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_org_permission_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_waiver_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_waiver_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_form_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_form_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_questions_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_questions_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_consent_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_consent_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_proposal_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_proposal_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_additional_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_recommendation', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_supervisor_signature', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_signature_date', sa.DateTime(), nullable=True))
    op.add_column('form_b', sa.Column('review_status', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('review_status1', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('rec_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.alter_column('form_b', 'declaration_date',
               existing_type=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('form_c', sa.Column('supervisor_org_permission_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_org_permission_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_waiver_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_waiver_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_form_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_form_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_questions_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_questions_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_consent_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_consent_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_proposal_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_proposal_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_additional_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_recommendation', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_supervisor_signature', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_signature_date', sa.DateTime(), nullable=True))
    op.add_column('form_c', sa.Column('review_status', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('review_status1', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('rec_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'rec_date')
    op.drop_column('form_c', 'review_status1')
    op.drop_column('form_c', 'review_status')
    op.drop_column('form_c', 'supervisor_signature_date')
    op.drop_column('form_c', 'supervisor_supervisor_signature')
    op.drop_column('form_c', 'supervisor_recommendation')
    op.drop_column('form_c', 'supervisor_additional_comments')
    op.drop_column('form_c', 'supervisor_proposal_comments')
    op.drop_column('form_c', 'supervisor_proposal_status')
    op.drop_column('form_c', 'supervisor_consent_comments')
    op.drop_column('form_c', 'supervisor_consent_status')
    op.drop_column('form_c', 'supervisor_questions_comments')
    op.drop_column('form_c', 'supervisor_questions_status')
    op.drop_column('form_c', 'supervisor_form_comments')
    op.drop_column('form_c', 'supervisor_form_status')
    op.drop_column('form_c', 'supervisor_waiver_comments')
    op.drop_column('form_c', 'supervisor_waiver_status')
    op.drop_column('form_c', 'supervisor_org_permission_comments')
    op.drop_column('form_c', 'supervisor_org_permission_status')
    op.alter_column('form_b', 'declaration_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               existing_nullable=True)
    op.drop_column('form_b', 'rec_date')
    op.drop_column('form_b', 'review_status1')
    op.drop_column('form_b', 'review_status')
    op.drop_column('form_b', 'supervisor_signature_date')
    op.drop_column('form_b', 'supervisor_supervisor_signature')
    op.drop_column('form_b', 'supervisor_recommendation')
    op.drop_column('form_b', 'supervisor_additional_comments')
    op.drop_column('form_b', 'supervisor_proposal_comments')
    op.drop_column('form_b', 'supervisor_proposal_status')
    op.drop_column('form_b', 'supervisor_consent_comments')
    op.drop_column('form_b', 'supervisor_consent_status')
    op.drop_column('form_b', 'supervisor_questions_comments')
    op.drop_column('form_b', 'supervisor_questions_status')
    op.drop_column('form_b', 'supervisor_form_comments')
    op.drop_column('form_b', 'supervisor_form_status')
    op.drop_column('form_b', 'supervisor_waiver_comments')
    op.drop_column('form_b', 'supervisor_waiver_status')
    op.drop_column('form_b', 'supervisor_org_permission_comments')
    op.drop_column('form_b', 'supervisor_org_permission_status')
    op.alter_column('form_a', 'supervisor_date',
               existing_type=sa.DateTime(timezone=255),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.alter_column('form_a', 'declaration_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(collation='Latin1_General_CI_AS'),
               existing_nullable=True)
    op.drop_column('form_a', 'rec_date')
    op.drop_column('form_a', 'review_status1')
    op.drop_column('form_a', 'review_status')
    op.drop_column('form_a', 'supervisor_signature_date')
    op.drop_column('form_a', 'supervisor_supervisor_signature')
    op.drop_column('form_a', 'supervisor_recommendation')
    op.drop_column('form_a', 'supervisor_additional_comments')
    op.drop_column('form_a', 'supervisor_proposal_comments')
    op.drop_column('form_a', 'supervisor_proposal_status')
    op.drop_column('form_a', 'supervisor_consent_comments')
    op.drop_column('form_a', 'supervisor_consent_status')
    op.drop_column('form_a', 'supervisor_questions_comments')
    op.drop_column('form_a', 'supervisor_questions_status')
    op.drop_column('form_a', 'supervisor_form_comments')
    op.drop_column('form_a', 'supervisor_form_status')
    op.drop_column('form_a', 'supervisor_waiver_comments')
    op.drop_column('form_a', 'supervisor_waiver_status')
    op.drop_column('form_a', 'supervisor_org_permission_comments')
    op.drop_column('form_a', 'supervisor_org_permission_status')
    # ### end Alembic commands ###
