"""Add or update tables

Revision ID: c1bb1039b5b5
Revises: 5ba2678faf02
Create Date: 2025-07-20 14:32:36.440004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bb1039b5b5'
down_revision: Union[str, None] = '5ba2678faf02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('certificate_received', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('certificate_received', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('certificate_received', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'certificate_received')
    op.drop_column('form_b', 'certificate_received')
    op.drop_column('form_a', 'certificate_received')
    # ### end Alembic commands ###
