"""initial_migration

Revision ID: c40ba8228910
Revises: 
Create Date: 2025-05-20 13:23:59.183779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'c40ba8228910'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_b_requirements')
    op.add_column('form_b', sa.Column('applicant_name', sa.String(length=120), nullable=True))
    op.add_column('form_b', sa.Column('student_number', sa.String(length=50), nullable=True))
    op.add_column('form_b', sa.Column('institution', sa.String(length=120), nullable=True))
    op.add_column('form_b', sa.Column('department', sa.String(length=120), nullable=True))
    op.add_column('form_b', sa.Column('degree', sa.String(length=120), nullable=True))
    op.add_column('form_b', sa.Column('study_title', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('mobile', sa.String(length=30), nullable=True))
    op.add_column('form_b', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('form_b', sa.Column('supervisor', sa.String(length=120), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_b', 'supervisor_email')
    op.drop_column('form_b', 'supervisor')
    op.drop_column('form_b', 'email')
    op.drop_column('form_b', 'mobile')
    op.drop_column('form_b', 'study_title')
    op.drop_column('form_b', 'degree')
    op.drop_column('form_b', 'department')
    op.drop_column('form_b', 'institution')
    op.drop_column('form_b', 'student_number')
    op.drop_column('form_b', 'applicant_name')
    op.create_table('form_b_requirements',
    sa.Column('id', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('needs_permission', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('permission_letter_path', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('has_prior_clearance', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('prior_clearance_path', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('company_requires_jbs', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('research_tools_path', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('proposal_path', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('impact_assessment_path', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__form_b_r__3213E83F4DAFB4E6')
    )
    # ### end Alembic commands ###
