"""Fix watched table

Revision ID: cf237ad1de03
Revises: 2cf57b8972c9
Create Date: 2025-06-18 19:53:32.483741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf237ad1de03'
down_revision: Union[str, None] = '2cf57b8972c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('supervisor_org_permission_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_org_permission_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_waiver_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_waiver_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_form_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_form_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_questions_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_questions_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_consent_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_consent_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_proposal_status', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_proposal_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_additional_comments', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_recommendation', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_supervisor_signature', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_signature_date', sa.DateTime(), nullable=True))
    op.alter_column('form_a', 'supervisor_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('form_b', sa.Column('supervisor_org_permission_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_org_permission_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_waiver_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_waiver_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_form_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_form_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_questions_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_questions_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_consent_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_consent_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_proposal_status', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_proposal_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_additional_comments', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_recommendation', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_supervisor_signature', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('supervisor_signature_date', sa.DateTime(), nullable=True))
    op.alter_column('form_b', 'supervisor_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('form_c', sa.Column('supervisor_org_permission_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_org_permission_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_waiver_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_waiver_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_form_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_form_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_questions_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_questions_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_consent_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_consent_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_proposal_status', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_proposal_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_additional_comments', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_recommendation', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_supervisor_signature', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('supervisor_signature_date', sa.DateTime(), nullable=True))
    op.alter_column('form_c', 'supervisor_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_c', 'supervisor_date',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.drop_column('form_c', 'supervisor_signature_date')
    op.drop_column('form_c', 'supervisor_supervisor_signature')
    op.drop_column('form_c', 'supervisor_recommendation')
    op.drop_column('form_c', 'supervisor_additional_comments')
    op.drop_column('form_c', 'supervisor_proposal_comments')
    op.drop_column('form_c', 'supervisor_proposal_status')
    op.drop_column('form_c', 'supervisor_consent_comments')
    op.drop_column('form_c', 'supervisor_consent_status')
    op.drop_column('form_c', 'supervisor_questions_comments')
    op.drop_column('form_c', 'supervisor_questions_status')
    op.drop_column('form_c', 'supervisor_form_comments')
    op.drop_column('form_c', 'supervisor_form_status')
    op.drop_column('form_c', 'supervisor_waiver_comments')
    op.drop_column('form_c', 'supervisor_waiver_status')
    op.drop_column('form_c', 'supervisor_org_permission_comments')
    op.drop_column('form_c', 'supervisor_org_permission_status')
    op.alter_column('form_b', 'supervisor_date',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.drop_column('form_b', 'supervisor_signature_date')
    op.drop_column('form_b', 'supervisor_supervisor_signature')
    op.drop_column('form_b', 'supervisor_recommendation')
    op.drop_column('form_b', 'supervisor_additional_comments')
    op.drop_column('form_b', 'supervisor_proposal_comments')
    op.drop_column('form_b', 'supervisor_proposal_status')
    op.drop_column('form_b', 'supervisor_consent_comments')
    op.drop_column('form_b', 'supervisor_consent_status')
    op.drop_column('form_b', 'supervisor_questions_comments')
    op.drop_column('form_b', 'supervisor_questions_status')
    op.drop_column('form_b', 'supervisor_form_comments')
    op.drop_column('form_b', 'supervisor_form_status')
    op.drop_column('form_b', 'supervisor_waiver_comments')
    op.drop_column('form_b', 'supervisor_waiver_status')
    op.drop_column('form_b', 'supervisor_org_permission_comments')
    op.drop_column('form_b', 'supervisor_org_permission_status')
    op.alter_column('form_a', 'supervisor_date',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.drop_column('form_a', 'supervisor_signature_date')
    op.drop_column('form_a', 'supervisor_supervisor_signature')
    op.drop_column('form_a', 'supervisor_recommendation')
    op.drop_column('form_a', 'supervisor_additional_comments')
    op.drop_column('form_a', 'supervisor_proposal_comments')
    op.drop_column('form_a', 'supervisor_proposal_status')
    op.drop_column('form_a', 'supervisor_consent_comments')
    op.drop_column('form_a', 'supervisor_consent_status')
    op.drop_column('form_a', 'supervisor_questions_comments')
    op.drop_column('form_a', 'supervisor_questions_status')
    op.drop_column('form_a', 'supervisor_form_comments')
    op.drop_column('form_a', 'supervisor_form_status')
    op.drop_column('form_a', 'supervisor_waiver_comments')
    op.drop_column('form_a', 'supervisor_waiver_status')
    op.drop_column('form_a', 'supervisor_org_permission_comments')
    op.drop_column('form_a', 'supervisor_org_permission_status')
    # ### end Alembic commands ###
