"""Add missing columns to form_a_requirements

Revision ID: d140cf7e4c02
Revises: 6db063248446
Create Date: 2025-06-06 15:33:40.874970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'd140cf7e4c02'
down_revision: Union[str, None] = '6db063248446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_a', 'remove_identifiers',
               existing_type=mssql.BIT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('form_a', 'encryption',
               existing_type=mssql.BIT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('form_a', 'pseudonyms',
               existing_type=mssql.BIT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('form_a', 'focus_group_warning',
               existing_type=mssql.BIT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_a', 'focus_group_warning',
               existing_type=sa.String(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('form_a', 'pseudonyms',
               existing_type=sa.String(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('form_a', 'encryption',
               existing_type=sa.String(),
               type_=mssql.BIT(),
               existing_nullable=True)
    op.alter_column('form_a', 'remove_identifiers',
               existing_type=sa.String(),
               type_=mssql.BIT(),
               existing_nullable=True)
    # ### end Alembic commands ###
