"""Add or update tables

<<<<<<<< HEAD:alembic/versions/d52496dac550_initial_migration.py
Revision ID: d52496dac550
Revises: 
Create Date: 2025-08-15 00:03:02.943643
========
Revision ID: 8fbca84a9b91
Revises: 
Create Date: 2025-08-15 11:37:59.019406
>>>>>>>> e7f4bf27d14842bb4b474aa50f0646b4affc692e:alembic/versions/8fbca84a9b91_add_or_update_tables.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:alembic/versions/d52496dac550_initial_migration.py
revision: str = 'd52496dac550'
========
revision: str = '8fbca84a9b91'
>>>>>>>> e7f4bf27d14842bb4b474aa50f0646b4affc692e:alembic/versions/8fbca84a9b91_add_or_update_tables.py
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a_requirements', sa.Column('participation_info_sheet', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_a_requirements', 'participation_info_sheet')
    # ### end Alembic commands ###
