"""Add missing columns to form_a_requirements

Revision ID: d551848b85ce
Revises: a87e20169099
Create Date: 2025-06-12 09:37:29.967514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd551848b85ce'
down_revision: Union[str, None] = 'a87e20169099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('org_permission_comment', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('waiver_comment', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('form_a_comment', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('questions_comment', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('consent_comment', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('proposal_comment', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('supervisor_feedback', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('recommendation', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('signature_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_a', 'signature_date')
    op.drop_column('form_a', 'recommendation')
    op.drop_column('form_a', 'supervisor_feedback')
    op.drop_column('form_a', 'proposal_comment')
    op.drop_column('form_a', 'consent_comment')
    op.drop_column('form_a', 'questions_comment')
    op.drop_column('form_a', 'form_a_comment')
    op.drop_column('form_a', 'waiver_comment')
    op.drop_column('form_a', 'org_permission_comment')
    # ### end Alembic commands ###
