"""Add or update tables

Revision ID: db60c48ffce7
Revises: c1bb1039b5b5
Create Date: 2025-07-22 18:00:15.940558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db60c48ffce7'
down_revision: Union[str, None] = 'c1bb1039b5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticate_student', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticate_student')
    # ### end Alembic commands ###
