"""Initial migration

Revision ID: e0244f556784
Revises: 
Create Date: 2025-07-22 16:25:46.386433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0244f556784'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rec',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('rec_id', sa.String(length=255), nullable=True),
    sa.Column('form_id', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('rec_comments', sa.String(), nullable=True),
    sa.Column('rec_status', sa.String(), nullable=True),
    sa.Column('rec_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('form_a', sa.Column('submitted_to_rec', sa.Boolean(), nullable=True))
    op.add_column('form_a', sa.Column('certificate_received', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('submitted_to_rec', sa.Boolean(), nullable=True))
    op.add_column('form_b', sa.Column('certificate_received', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('submitted_to_rec', sa.Boolean(), nullable=True))
    op.add_column('form_c', sa.Column('certificate_received', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'certificate_received')
    op.drop_column('form_c', 'submitted_to_rec')
    op.drop_column('form_b', 'certificate_received')
    op.drop_column('form_b', 'submitted_to_rec')
    op.drop_column('form_a', 'certificate_received')
    op.drop_column('form_a', 'submitted_to_rec')
    op.drop_table('rec')
    # ### end Alembic commands ###
