"""Fix watched table

Revision ID: e98edf0bfbe8
Revises: 82628a0d1b55
Create Date: 2025-06-22 12:45:17.631574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98edf0bfbe8'
down_revision: Union[str, None] = '82628a0d1b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_a', sa.Column('certificate_valid_years', sa.String(), nullable=True))
    op.add_column('form_a', sa.Column('certificate_end_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('form_a', sa.Column('certificate_issuer', sa.String(length=255), nullable=True))
    op.add_column('form_a', sa.Column('certificate_email', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('certificate_valid_years', sa.String(), nullable=True))
    op.add_column('form_b', sa.Column('certificate_end_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('form_b', sa.Column('certificate_issuer', sa.String(length=255), nullable=True))
    op.add_column('form_b', sa.Column('certificate_email', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('certificate_valid_years', sa.String(), nullable=True))
    op.add_column('form_c', sa.Column('certificate_end_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('form_c', sa.Column('certificate_issuer', sa.String(length=255), nullable=True))
    op.add_column('form_c', sa.Column('certificate_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_c', 'certificate_email')
    op.drop_column('form_c', 'certificate_issuer')
    op.drop_column('form_c', 'certificate_end_date')
    op.drop_column('form_c', 'certificate_valid_years')
    op.drop_column('form_b', 'certificate_email')
    op.drop_column('form_b', 'certificate_issuer')
    op.drop_column('form_b', 'certificate_end_date')
    op.drop_column('form_b', 'certificate_valid_years')
    op.drop_column('form_a', 'certificate_email')
    op.drop_column('form_a', 'certificate_issuer')
    op.drop_column('form_a', 'certificate_end_date')
    op.drop_column('form_a', 'certificate_valid_years')
    # ### end Alembic commands ###
