"""Add form_c table

Revision ID: f964c4849959
Revises: 5e90283d983d
Create Date: 2025-05-31 12:15:33.147137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f964c4849959'
down_revision: Union[str, None] = '5e90283d983d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_c', sa.Column('summary_title', sa.Text(), nullable=True))
    op.alter_column('form_c', 'project_title',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('form_c', 'project_title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('form_c', 'summary_title')
    # ### end Alembic commands ###
